=== sosa-rcrdt/tecweb/practicas/p16/serviciovod.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="regionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MEX"/>
            <xs:enumeration value="USA"/>
            <xs:enumeration value="ESP"/>
            <xs:enumeration value="ARG"/>
            <xs:enumeration value="KOR"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="CatalogoVOD">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cuenta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="perfiles">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="perfil" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                                <xs:attribute name="idioma" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="correo" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contenido">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="peliculas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="genero" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                                                            <xs:attribute name="duracion" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="region" type="regionType" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="series">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="genero" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                                                            <xs:attribute name="duracion" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nombre" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="region" type="regionType" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sosa-rcrdt/tecweb/practicas/p15/serviciovod4N.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogovod.xsl"?>
<CatalogoVOD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="serviciovod.xsd">

    <cuenta correo="sosafco3@gmail.com">
        <perfiles>
            <perfil nombre="Nelson" idioma="Español" />
            <perfil nombre="Richard" idioma="Inglés" />
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas region="MEX"> <!-- Se añade el atributo "region" con valor "MEX" -->
            <genero nombre="Comedia">
                <titulo nombre="La Gran Aventura Lego" duracion="100 minutos" />
                <titulo nombre="Supercool" duracion="113 minutos" />
                <titulo nombre="Zombieland" duracion="88 minutos" />
                <titulo nombre="Jumanji: Bienvenidos a la Jungla" duracion="119 minutos" />
            </genero>
            <genero nombre="Romance">
                <titulo nombre="La La Land" duracion="128 minutos" />
                <titulo nombre="El Diario de una Pasión" duracion="123 minutos" />
                <titulo nombre="Orgullo y Prejuicio" duracion="129 minutos" />
                <titulo nombre="Antes de Amanecer" duracion="101 minutos" />
            </genero>
        </peliculas>
        <series region="USA">
            <genero nombre="Documentales">
                <titulo nombre="Planeta Tierra" duracion="11 episodios" />
                <titulo nombre="Cosmos" duracion="13 episodios" />
                <titulo nombre="Nuestro Planeta" duracion="8 episodios" />
                <titulo nombre="Vida" duracion="10 episodios" />
            </genero>
            <genero nombre="Animación">
                <titulo nombre="Avatar: La Leyenda de Aang" duracion="61 episodios" />
                <titulo nombre="Gravity Falls" duracion="40 episodios" />
                <titulo nombre="Rick y Morty" duracion="61 episodios" />
                <titulo nombre="BoJack Horseman" duracion="77 episodios" />
            </genero>
        </series>
    </contenido>
</CatalogoVOD>
